### ISSUE TITLE
Parsing geojson or wkt with Swedish culture throws exception

### ISSUE THREAD

**Issue by peter-eriksson** [songjiahong/Geo.Library#1]
When parsing points with decimals in a system that is using a Swedish culture I get an exception.
Some countries are using comma sign as a decimal separator: https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma

**Example:**

`GeoJsonReader.Read("{\"type\": \"Point\",\"coordinates\": [10.1, 20.2]}")`

will thrown (in a thread with CultureInfo "sv-SE")

```
  Error Message:
   System.FormatException : Input string was not in a correct format.
  Stack Trace:
   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at GeoLibrary.IO.GeoJson.GeoJsonReader.ReadDouble(TextReader reader, StringBuilder builder) in /GeoLibrary/IO/GeoJson/GeoJsonReader.cs:line 246
   at GeoLibrary.IO.GeoJson.GeoJsonReader.ReadPoint(TextReader reader, StringBuilder builder, Boolean verifyBeginning) in /GeoLibrary/IO/GeoJson/GeoJsonReader.cs:line 256
   at GeoLibrary.IO.GeoJson.GeoJsonReader.ParseJsonObject(TextReader reader, StringBuilder builder, JsonObject& jsonObject) in /GeoLibrary/IO/GeoJson/GeoJsonReader.cs:line 136
   at GeoLibrary.IO.GeoJson.GeoJsonReader.ParseObject(String json) in /GeoLibrary/IO/GeoJson/GeoJsonReader.cs:line 63
   at GeoLibrary.IO.GeoJson.GeoJsonReader.Read(String json) in /GeoLibrary/IO/GeoJson/GeoJsonReader.cs:line 20
```

**Comment by songjiahong** [comment]
Thanks @peter-eriksson
